/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/components/ModalDatePicker`; params?: Router.UnknownInputParams; } | { pathname: `/components/ModalPicker`; params?: Router.UnknownInputParams; } | { pathname: `/config/const`; params?: Router.UnknownInputParams; } | { pathname: `/config/script`; params?: Router.UnknownInputParams; } | { pathname: `/config/station_name`; params?: Router.UnknownInputParams; } | { pathname: `/services`; params?: Router.UnknownInputParams; } | { pathname: `/services/plugin`; params?: Router.UnknownInputParams; } | { pathname: `/services/webviewFetcher`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ModalDatePicker`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ModalPicker`; params?: Router.UnknownOutputParams; } | { pathname: `/config/const`; params?: Router.UnknownOutputParams; } | { pathname: `/config/script`; params?: Router.UnknownOutputParams; } | { pathname: `/config/station_name`; params?: Router.UnknownOutputParams; } | { pathname: `/services`; params?: Router.UnknownOutputParams; } | { pathname: `/services/plugin`; params?: Router.UnknownOutputParams; } | { pathname: `/services/webviewFetcher`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/components/ModalDatePicker${`?${string}` | `#${string}` | ''}` | `/components/ModalPicker${`?${string}` | `#${string}` | ''}` | `/config/const${`?${string}` | `#${string}` | ''}` | `/config/script${`?${string}` | `#${string}` | ''}` | `/config/station_name${`?${string}` | `#${string}` | ''}` | `/services${`?${string}` | `#${string}` | ''}` | `/services/plugin${`?${string}` | `#${string}` | ''}` | `/services/webviewFetcher${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/components/ModalDatePicker`; params?: Router.UnknownInputParams; } | { pathname: `/components/ModalPicker`; params?: Router.UnknownInputParams; } | { pathname: `/config/const`; params?: Router.UnknownInputParams; } | { pathname: `/config/script`; params?: Router.UnknownInputParams; } | { pathname: `/config/station_name`; params?: Router.UnknownInputParams; } | { pathname: `/services`; params?: Router.UnknownInputParams; } | { pathname: `/services/plugin`; params?: Router.UnknownInputParams; } | { pathname: `/services/webviewFetcher`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
